spring:
  datasource:
    url: jdbc:h2:mem:wwc2023
    username: wwc2023
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

openai:
  api-key: ${OPENAI_API_KEY}